// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cO51Q4SKqS7BgXoN1d5ogGvaqyKBzns',
    appId: '1:191439383511:web:c48182c824eb26f3443992',
    messagingSenderId: '191439383511',
    projectId: 'amc-online',
    authDomain: 'amc-online.firebaseapp.com',
    storageBucket: 'amc-online.appspot.com',
    measurementId: 'G-FW050V9JZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCme6XGeIku1AOwYx1elzSEn2m6TjewZ1A',
    appId: '1:191439383511:android:ad9c4ab1b7363f74443992',
    messagingSenderId: '191439383511',
    projectId: 'amc-online',
    storageBucket: 'amc-online.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaJNLRu48lZshVfCrTPIiRF2tHe0atlh0',
    appId: '1:191439383511:ios:23e06fddfc9b199d443992',
    messagingSenderId: '191439383511',
    projectId: 'amc-online',
    storageBucket: 'amc-online.appspot.com',
    iosClientId: '191439383511-4n3fipmn5m54dq4silmmlib18ur332t4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaJNLRu48lZshVfCrTPIiRF2tHe0atlh0',
    appId: '1:191439383511:ios:25600cf7c9cad574443992',
    messagingSenderId: '191439383511',
    projectId: 'amc-online',
    storageBucket: 'amc-online.appspot.com',
    iosClientId: '191439383511-bod2h5qitr54m6g760og7u8nbs0ea7ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
